# Form implementation generated from reading ui file '.\ui\dialogadmin.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.descroptionLabel = QtWidgets.QLabel(parent=Dialog)
        self.descroptionLabel.setObjectName("descroptionLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.descroptionLabel)
        self.descroptionLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.descroptionLineEdit.setObjectName("descroptionLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.descroptionLineEdit)
        self.priceLabel = QtWidgets.QLabel(parent=Dialog)
        self.priceLabel.setObjectName("priceLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.priceLabel)
        self.priceLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.priceLineEdit)
        self.quantityLabel = QtWidgets.QLabel(parent=Dialog)
        self.quantityLabel.setObjectName("quantityLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.quantityLabel)
        self.quantityLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.quantityLineEdit.setObjectName("quantityLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.quantityLineEdit)
        self.imageLabel = QtWidgets.QLabel(parent=Dialog)
        self.imageLabel.setObjectName("imageLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.imageLabel)
        self.imageLineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.imageLineEdit.setObjectName("imageLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.imageLineEdit)
        self.pushButton_load = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_load.setObjectName("pushButton_load")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.pushButton_load)
        self.verticalLayout.addLayout(self.formLayout)
        self.pushButton_save = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout.addWidget(self.pushButton_save, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.descroptionLabel.setText(_translate("Dialog", "descroption"))
        self.priceLabel.setText(_translate("Dialog", "price"))
        self.quantityLabel.setText(_translate("Dialog", "quantity"))
        self.imageLabel.setText(_translate("Dialog", "image"))
        self.pushButton_load.setText(_translate("Dialog", "Загрузить фото"))
        self.pushButton_save.setText(_translate("Dialog", "Сохранить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
